# This configuration is a placeholder. Replace any values with relevant values for your
# service controller project.
---
annotations:
  capabilityLevel: Basic Install
  shortDescription: AWS Elastic Disaster Recovery controller is a service controller for managing Elastic Disaster Recovery resources
    in Kubernetes
displayName: AWS Controllers for Kubernetes - Amazon Elastic Disaster Recovery
description: |-
  Manage Amazon Elastic Disaster Recovery resources in AWS from within your Kubernetes cluster.


  **About Amazon Elastic Disaster Recovery**


  AWS Elastic Disaster Recovery (AWS DRS) minimizes downtime and data loss with fast, reliable recovery of on-premises and cloud-based applications using affordable storage, minimal compute, and point-in-time recovery.


  **About the AWS Controllers for Kubernetes**


  This controller is a component of the [AWS Controller for Kubernetes](https://github.com/aws/aws-controllers-k8s)
  project. This project is currently in **developer preview**.


  **Pre-Installation Steps**


  Please follow the following link: [Red Hat OpenShift](https://aws-controllers-k8s.github.io/community/docs/user-docs/openshift/)
samples:
- kind: SourceServer
  spec: '{}'
- kind: RecoveryServer
  spec: '{}'
maintainers:
- name: "elastic disaster recovery maintainer team"
  email: "ack-maintainers@amazon.com"
links:
- name: Amazon Elastic Disaster Recovery Developer Resources
  url: https://aws.amazon.com/disaster-recovery/resources/
